version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
volumes:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/node_project/
      o: bind

networks:
  app-network:
    driver: bridge  
