version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "80:3000"
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nodejs
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email messanchristian@hotmail.com --agree-tos --no-eff-email --staging -d restapi.cogenius.shop  -d www.restapi.cogenius.shop 

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/refacc/node_project/views/
      o: bind

networks:
  app-network:
    driver: bridge  